<?php include('lib/header.php') ?>  

<div id="contentwrap"> 
	<div id="content">  
	
<?php include('navegador.php') ?> 
	
	<div id="content-in">
		<div id="left-menu">
			<ul>
				<a href="chopo.php"><li>Bienvenida</li></a>
				<a href="responsabilidad-social.php"><li>Responsabilidad Social</li></a>
				<a href="sitios-de-interes.php"><li>Sitios de Intéres</li></a>
				<a href="politicas-de-privacidad.php"><li>Políticas de Privacidad</li></a>
				<a href="bolsa-de-trabajo.php"><li>Bolsa de Trabajo</li></a>
				<a href="noticias.php"><li>Noticias</li></a>
				<!--<a href="tarjeta-privilegios.php"><li>Tarjeta Privilegios Chopo</li></a>-->
				<a href="terminos-de-uso.php"><li>Términos de uso</li></a>
				<a href="legales.php"><li>Legales</li></a>
				<a href="aviso-de-privacidad.php"><li style="border-bottom:none" class="select">Aviso de Privacidad</li></a>
			</ul>
		</div>
		
		<div id="right-content" class="avisoprivacidad">
			<h1><strong>AVISO DE PRIVACIDAD</strong></h1>
<p><strong>Artículo 16</strong></p>
<h2><strong>RESPONSABLE I</strong></h2>
<p>LABORATORIO MÉDICO DEL CHOPO (GRUPO DIAGNÓSTICO MÉDICO PROA, S.A. DE C.V. ), CON DOMICILIO EN CALLE ALFONSO HERRERA NUMERO 75, COLONIA SAN RAFAEL, DELEGACION CUAUHTEMOC, C.P. 06470, DISTRITO FEDERAL, ES RESPONSABLE DEL TRATAMIENTO DE SUS DATOS PERSONALES.</p>
<h2><strong>CONTACTO</strong></h2>
<p>OFICINA DE PRIVACIDAD: DEPARTAMENTO DE CONTROL DE DATOS PERSONALES</p>
<p>DOMICILIO: ALFONSO HERRERA NUMERO 75, COLONIA SAN RAFAEL, DELEGACION CUAUHTEMOC, C.P. 06470, MEXICO, DISTRITO FEDERAL</p>
<p>CORREO ELECTRÓNICO: <a href="mailto:edgar.osorio@proa.com.mx">edgar.osorio@proa.com.mx</a></p>
<p>TELÉFONO: 1946-1000 EXT. 51459 o 53249</p>
<p>RESPONSABLE DE AREA: Edgar Osorio Morales</p>
<h2><strong>FINALIDAD II</strong></h2>
<p><strong>SUS DATOS PERSONALES SERÁN UTILIZADOS CON LA FINALIDAD DE:</strong></p>
<ul>
  <li>PROVEER NUESTROS SERVICIOS Y PRODUCTOS.</li>
  <li>INFORMAR SOBRE CAMBIOS O NUEVOS PRODUCTOS Y SERVICIOS</li>
  <li>DAR CUMPLIMIENTO A LAS OBLIGACIONES CONTRAIDAS CON NUESTROS CLIENTES</li>
  <li>EVALUAR LA CALIDAD EN EL SERVICIO</li>
</ul>
<p><strong>PARA LAS FINALIDADES SEÑALADAS EN EL PRESENTE AVISO DE PRIVACIDAD, PODEMOS RECABAR SUS DATOS PERSONALES DE DISTINTAS FORMAS:</strong></p>
<ul>
  <li>CUANDO USTED NOS LOS PROPORCIONA DIRECTAMENTE</li>
  <li>CUANDO UTILIZA NUESTRO SERVICIO DE CITAS TELEFONICAS</li>
  <li>CUANDO SOLICITAN INFORMES DE NUESTROS SERVICIOS</li>
</ul>
<p>DATOS PERSONALES QUE RECABAMOS DE MANERA DIRECTA:</p>
<ul>
  <li>NOMBRE COMPLETO</li>
  <li>SEXO</li>
  <li>DIRECCION</li>
  <li>TELÉFONOS DE CONTACTO</li>
  <li><strong>EMAIL</strong></li>
  <li>FECHA DE NACIMIENTO</li>
  <li>OCUPACIÓN</li>
  <li>ESTADO CIVIL</li>
  <li>ESCOLARIDAD</li>
  <li>DEPENDIENTES ECONÓMICOS</li>
  <li>DATOS DEL CONYUGE</li>
</ul>
<p>DATOS PERSONALES QUE RECABAMOS A TRAVÉS DE NUESTRO SISTEMA DE CITAS TELEFÓNICAS:</p>
<ul>
  <li>NOMBRE COMPLETO</li>
  <li>DIRECCIÓN</li>
  <li>TELÉFONOS DE CONTACTOS</li>
</ul>
<h2><strong>DATOS PERSONALES SENSIBLES ART. 2 FRACC VI</strong></h2>
<p>LE INFORMAMOS QUE PARA CUMPLIR CON LAS FINALIDADES PREVISTAS EN ESTE AVISO DE PRIVACIDAD, SERAN RECABADOS Y TRATADOS DATOS PERSONALES SENSIBLES, COMO AQUELLOS QUE REFIEREN A ASPECTOS SENSIBLES COMO EL ORIGEN RACIAL O ETNICO, ESTADO DE SALUD PRESENTE Y FUTURO, INFORMACION GENETICA, CREENCIAS RELIGIOSAS, FILOSOFICAS Y MORALES, AFILIACION SINDICAL, OPINIONES POLITICAS Y/O PREFERENCIA SEXUAL.</p>
<p>NOS COMPROMETEMOS A QUE LOS MISMOS SERAN TRATADOS BAJO LAS MAS ESTRICTAS MEDIDAS DE SEGURIDAD QUE GARANTICEN SU CONFIDENCIALIDAD.</p>

<p>POR LO QUE, DE CONFORMIDAD CON LO QUE ESTABLECE EL ARTÍCULO 9 DE LA LEY FEDERAL DE PROTECCION DE DATOS PERSONALES EN POSESION DE LOS PARTICULARES, <em>REQUERIMOS DE SU CONSENTIMIENTO EXPRESO PARA EL TRATAMIENTO DE SUS DATOS PERSONALES SENSIBLES</em>POR LO QUE SOLICITAMOS INDIQUE SI ACEPTA O NO EL TRATAMIENTO</p>

<p>
  <input checked="checked" type="checkbox" value="Butter" />
   CONSIENTO QUE MIS DATOS PERSONALES SENSIBLES SEAN TRATADOS CONFORME A LOS TERMINOS Y CONDICIONES DEL PRESENTE AVISO DE PRIVACIDAD.</p>
<p> </p>
<p> </p>
<p> </p>
<p>_____________________________________________</p>
<p><em>NOMBRE Y FIRMA DEL TITULAR</em></p>
<h2><strong>LIMITACIÓN DEL USO O DIVULGACION </strong>DE DATOS PERSONALES III</h2>
<p>(PARA EL CASO DE USO DE DATOS PROMOCIONALES CON LA FINALIDAD DE EMITIR PUBLICIDAD)</p>

<p>USTED PUEDE DEJAR DE RECIBIR CORREOS ELECTRÓNICOS PROMOCIONALES A TRAVES DE LA SIGUIENTE SOLICITUD:</p>

<ul>
  <li>INGRESE A NUESTRA PÁGINA DE INTERNET</li>
  <li>CLICK EN EL LINK DE AVISO DE PRIVACIDAD</li>
  <li>CLICK EN EL LINK DE LIMITACION DE USO O DIVUGACION DE DATOS PERSONALES</li>
  <li>LLENE LOS CAMPOS DEL FORMULARIO</li>
  <li>INDIQUE DE MANERA PRECISA, LA FORMA EN QUE SE LE DEBA DE NOTIFICAR DICHA RESOLUCION (TELÉFONO, CORREO ELECTRÓNICO)</li>
</ul>

<p>USTED RECIBIRÁ RESPUESTA DE NUESTRO DEPARTAMENTO, EN UN LAPSO NO MAYOR A 8 DIAS HÁBILES CONTADOS A PARTIR DE LA FECHA DE RECEPCION DE SU SOLICITUD; EN CASO DE SER APROBADA, SE REALIZARÁ LA CANCELACIÓN DENTRO DE LOS 8 DÍAS POSTERIORES A LA NOTIFICACIÓN DE APROBACIÓN.</p>

<h2><strong>PARA EJERCITAR SUS DERECHOS A.R.C.O. </strong>(ACCESO, RECTIFICACION, CANCELACION U OPOSICION).</h2>

<p><strong>¿QUE SON LOS DERECHOS ARCO?</strong></p>

<p>ES EL DERECHO QUE TIENE USTED COMO TITULAR DE LOS DATOS RECABADOS POR NUESTRA EMPRESA DE ACCEDER, RECTIFICAR, CANCELAR U OPONERSE AL USO DE SUS DATOS PERSONALES</p>

<p>USTED TIENE DERECHO DE ACCEDER A SUS DATOS PERSONALES QUE POSEEMOS Y A LOS DETALLES DEL TRATAMIENTO DE LOS MISMOS, ASÍ COMO A RECTIFICAR LOS MISMOS EN CASO DE SER INEXACTOS O INCOMPLETOS; CANCELARLOS CUANDO CONSIDERE QUE NO SE REQUIEREN PARA ALGUNA DE LAS FINALIDADES SEÑALADAS EN EL PRESENTE AVISO DE PRIVACIDAD, ESTEN SIENDO UTILIZADOS PARA FINALIDADES NO CONSENTIDAS O HAYA FINALIZADO LA RELACION CONTRACTUAL O DE SERVICIO, O BIEN, OPONERSE AL TRATAMIENTO DE LOS MISMOS PARA FINES ESPECIFICOS.</p>

<p>EL MECANISMO QUE SE HA IMPLEMENTADO PARA EL EJERCICIO DE DICHOS DERECHOS ES:</p>

<ul>
  <li>SOLICITUD A TRAVES DE ESCRITO LIBRE</li>
  <li>DIRIJIDO AL ENCARGADO DEL DEPARTAMENTO DE CONTROL DE DATOS PERSONALES</li>
  <li>NOMBRE COMPLETO DEL TITULAR DE LOS DERECHOS</li>
  <li>EN SU ESCRITO DEBERA REDACTAR DE FORMA CLARA Y ESPECIFICA LA(S) RAZÓN(ES) POR LA(S) QUE DESEA EJERCER SU(S) DERECHO(S).</li>
  <li>MANIFESTAR EL MEDIO EN EL QUE DEBA DE RECIBIR LA NOTIFICACION DE RESPUESTA (TELEFONO, CORREO ELECTRONICO, ETC.)</li>
  <li>FIRMA DEL TITULAR DE LOS DERECHOS</li>
  <li>PARA EL CASO DE CONTAR CON REPRESENTANTE LEGAL, DEBERÁ ACOMPAÑAR EN COPIA SIMPLE EL INSTRUMENTO QUE ACREDITE TAL PERSONALIDAD, ASÍ COMO COPIA SIMPLE DE IDENTIFICACION OFICIAL (CREDENCIAL PARA VOTAR CON FOTOGRAFIA, CEDULA PROFESIONAL O CARTILLA MILITAR)</li>
  <li>EL ESCRITO DEBERA PRESENTRSE EN LA DIRECCION DE LA OFICINA DE CONTROL DE DATOS PERSONALES, UBICADA EN ALFONSO HERRERA NUMERO 75, COLONIA SAN RAFAEL, DELEGACION CUAUHTEMOC, C.P. 06470, DISTRITO FEDERAL, O EN SU DEFECTO, PARA AQUELLOS TITULARES QUE SE ENCUENTREN FUERA DEL DISTRITO FEDERAL Y REQUIERAN EJERCER SUS DERECHOS, DEBERAN ACUDR A LA SUCURSAL MAS CERCANA DE SU LOCALIDAD, Y PRESENTAR SU ESCRITO ANTE EL RESPONSABLE DEL ESTABLECIMIENTO, QUIEN TENDRÁ LA OBLIGACION DE ENVIAR A LA OFICINA DE CONTROL DE DATOS PERSONALES EN UN PLAZO NO MAYOR DE 3 DIAS HABILES.</li>
</ul>

<p>UNA VEZ RECIBIDO EL ESCRITO, EL ENCARGADO DEL DEPARTAMENTO, EN UN PLAZO NO MAYOR A 10 DIAS HABILES, DARÁ RESPUESTA A SU SOLICITUD A TRAVES DEL MEDIO QUE INDICO EL TITULAR; POSTERIOR A LA FECHA DE NOTIFICACION, TANTO EL TITULAR COMO EL ENCARGADO DEL DEPARTAMENTO, REALIZARAN LAS ACCIONES NECESARIAS A EFECTO DE ACCEDER, RECTIFICAR, CORREGIR U OPONERSE RESPECTO DEL TRATAMIENTO DE DATOS PERSONALES DEL INTERESADO.</p>

<p>PARA MAYOR INFORMACIÓN, FAVOR DE COMUNICARSE A LA OFICINA DE CONTROL DE DATOS PERSONALES AL TELÉFONO 19461000 EXT  51459, CON EL SR. EDGAR OSORIO MORALES. EN UN HORARIO DE 09:00 A 17:00 HRS DE LUNES A VIERNES.</p>

<h2><strong>REVOCACION DEL CONSENTIMIENTO</strong></h2>
<p>EN TODO MOMENTO, USTED PUEDE REVOCAR EL CONSENTIMIENTO QUE NOS HA OTORGADO PARA EL TRATAMIENTO DE SUS DATOS PERSONALES, A FIN DE QUE DEJEMOS DE HACER USO DE LOS MISMOS, PARA ELLO, ES NECESARIO QUE PRESENTE SU PETICION POR ESCRITO, SIGUIENDO LAS MISMAS FORMALIDADES QUE SE MENCIONAN EN EL PUNTO ANTERIOR.</p>

<p>LA MECANICA PARA LA REVOCACIÓN DEL CONSENTIMIENTO SEGUIRÁ LOS MISMOS PLAZOS Y FORMALIDADES QUE SE MENIFIESTAN EN EL APARTADO DE EJERCICIO DE DERECHOS A.R.C.O.</p>

<h2><strong>TRANSFERENCIA DE DATOS V</strong></h2>
<p>SUS DATOS PERSONALES PUEDEN SER TRANSFERIDOS Y TRATADOS DENTRO Y FUERA DEL PAIS, POR PERSONAS DISTINTAS A ESTA EMPRESA. EN ESE SENTIDO, SU INFORMACION PUEDE SER COMPARTIDA CON ENTIDADES JUDICIALES, ESPECIALISTAS EN EL GIRO, Y CUALQUIER PERSONA O ENTIDADES LOCALES, ESTATALES O MUNICIPALES QUE LO SOLICITEN, SIEMPRE APEGANDONOS A LOS TERMINOS MARCADOS EN LA LEY RESPECTIVA.</p>

<p>GRUPO DIAGNOSTICO MEDICO PROA, S.A. DE C.V.  SE COMPROMETE A NO TRANSFERIR SU INFORMACION PERSONAL A TERCEROS SIN SU CONSENTIMIENTO, SALVO POR LAS SIGUIENTES EXCEPCIONES:</p>

<ul>
  <li>CUANDO LA TRANSFERENCIA SEA NECESARIA PARA LA PREVENCION O EL DIAGNOSTICO MEDICO, LA PRESTACION DE ASISTENCIA SANITARIA, TRATAMIENTO MEDICO O LA GESTION DE SERVICIOS SANITARIOS</li>
  <li>CUANDO LA TRANSFERENCIA SEA NECESARIA O LEGALMENTE EXIGIDA PARA LA SALVAGUARDA DE UN INTERES PÚBLICO O PARA LA PROCURACION O ADMINISTRACION DE JUSTICIA</li>
  <li>CUANDO LA TRANSFERENCIA SEA PRECISA PARA EL RECONOCIMIENTO, EJERCICIO O DEFENSA DE UN DERECHO EN PROCESO JUDICIAL</li>
  <li>CUANDO LA TRANSFERENCIA SEA PRECISA PARA EL MANTENIMIENTO O CUMPLIMIENTO DE UNA RELACION JURIDICA ENTRE EL RESPONSABLE Y EL TITULAR (ES EL CASO DE LICITACIONES Y CONTRATO DE PRESTACION DE SERVICIOS CON VOLUMEN DE CLIENTES)</li>
</ul>

<p>SI USTED<strong> NO </strong>MANIFIESTA EXPRESAMENTE SU OPOSICION PARA SUS DATOS PERSONALES SEAN TRANSFERIDOS, SE ENTENDERÁ QUE HA OROTGADO SU CONSENTIMIENTO PARA ELLO.</p>

<p>NO CONSIENTO QUE MIS DATOS PERSONALES SEAN TRANSFERIDOS EN LOS TERMINOS QUE SEÑALA EL PRESENTE AVISO DE PRIVACIDAD.</p>
<p> </p>
<p> </p>
<p> </p>
<p> </p>
<p>___________________________________________________</p>
<p><em>NOMBRE Y FIRMA AUTOGRAFA DEL TITULAR</em></p>
<h2><strong>MODIFICACIONES AL AVISO DE PRIVACIDAD VI</strong></h2>
<p>NOS RESERVAMOS EL DERECHO DE EFECTUAR EL CUALQUIER MOMENTO MODIFICACIONES O ACTUALIZACIONES AL PRESENTE AVISO DE PRIVACIDAD, PARA LA ATENCION DE POLITICAS INTERNAS O NUEVOS REQUERIMIENTOS PARA LA PRESTACION U OFRECIMIENTO DE NUESTROS SERVICIOS O PRODUCTOS.</p>

<p>ESTAS MODIFICACIONES ESTARAN DISPONIBLES AL PUBLICO A TRAVES NUESTRA PAGINA EN INTERNET EN <a href="http://www.chopo.com.mx/">www.chopo.com.mx</a> LA SECCION DE AVISO DE PRIVACIDAD, O COMO UN SERVICIO ESPECIAL, SE LAS HAREMOS LLEGAR AL CORREO ELECTRONICO QUE SE TENGA EN BASE DE DATOS.</p>
<h2><strong>QUEJAS Y DENUNCIAS</strong></h2>
<p>SI USTED CONSIDERA QUE SU DERECHO DE PROTECCION DE DATOS PERSONALES HA SIDO LESIONADO POR ALGUNA CONDUCTA DE NUESTROS COLABORADORES O DE NUESTRAS ACTUACIONES O RESPUESTAS, PRESUME QUE EL EN TRATAMIENTO DE SUS DATOS PERSONALES EXISTE ALGUNA VIOLACION A LAS DISPOSICIONES PREVISTAS EN LA LEY FEDERAL DE PROTECCION DE DATOS PERSONALES EN POSESIÓN DE LOS PARTICULARES, PODRA INTERPONER LA QUEJA O DENUNCIA CORRESPONDIENTE ANTE EL IFAI; PARA MAYOR INFORMACION VISITE <a href="http://www.ifai.org.mx/" target="_blank" style="color:blue">WWW.IFAI.ORG.MX</a></p>
		
		
		</div>
		<div style="clear:both"></div>
	</div>

	</div>
</div>
<?php include('lib/footer.php') ?>  